import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying Match Verifier contracts with account:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "C2FLR");

  // 1. Deploy MatchHistoryGroth16Verifier (generated by snarkjs)
  const Groth16Factory = await ethers.getContractFactory("MatchHistoryGroth16Verifier");
  const groth16Verifier = await Groth16Factory.deploy();
  await groth16Verifier.waitForDeployment();
  const groth16Address = await groth16Verifier.getAddress();
  console.log("MatchHistoryGroth16Verifier deployed to:", groth16Address);

  // 2. Deploy SkillProofMatchVerifier (wrapper)
  const MatchFactory = await ethers.getContractFactory("SkillProofMatchVerifier");
  const matchVerifier = await MatchFactory.deploy(groth16Address);
  await matchVerifier.waitForDeployment();
  const matchAddress = await matchVerifier.getAddress();
  console.log("SkillProofMatchVerifier deployed to:", matchAddress);

  // 3. Register a test commitment using AlphaTrader's seeded data
  // AlphaTrader: totalMatches=12, wins=8, salt=54321
  const totalMatches = 12;
  const wins = 8;
  const salt = 54321;
  const commitment = BigInt(totalMatches) + BigInt(wins) * 65536n + BigInt(salt) * 4294967296n;

  console.log("\nRegistering test commitment...");
  console.log(`  totalMatches: ${totalMatches}, wins: ${wins}, salt: ${salt}`);
  console.log(`  commitment: ${commitment}`);

  const tx = await matchVerifier.registerMatchCommitment(totalMatches, wins, salt);
  await tx.wait();
  console.log("Test commitment registered");

  // 4. Update deployments.json
  const libDir = path.join(__dirname, "..", "lib");
  const deploymentsPath = path.join(libDir, "deployments.json");
  const deployments = JSON.parse(fs.readFileSync(deploymentsPath, "utf-8"));

  const network = await ethers.provider.getNetwork();
  const networkName = network.chainId === 114n ? "coston2" : "localhost";

  if (!deployments[networkName]) {
    deployments[networkName] = {};
  }
  deployments[networkName].MatchHistoryGroth16Verifier = groth16Address;
  deployments[networkName].SkillProofMatchVerifier = matchAddress;
  fs.writeFileSync(deploymentsPath, JSON.stringify(deployments, null, 2) + "\n");
  console.log("Updated lib/deployments.json");

  // 5. Extract and save ABIs
  const groth16ArtifactPath = path.join(
    __dirname, "..", "artifacts", "contracts",
    "MatchHistoryVerifier.sol", "MatchHistoryGroth16Verifier.json"
  );
  const groth16Artifact = JSON.parse(fs.readFileSync(groth16ArtifactPath, "utf-8"));
  fs.writeFileSync(
    path.join(libDir, "match-history-verifier-abi.json"),
    JSON.stringify(groth16Artifact.abi, null, 2) + "\n"
  );
  console.log("Saved MatchHistoryGroth16Verifier ABI to lib/match-history-verifier-abi.json");

  const matchArtifactPath = path.join(
    __dirname, "..", "artifacts", "contracts",
    "SkillProofMatchVerifier.sol", "SkillProofMatchVerifier.json"
  );
  const matchArtifact = JSON.parse(fs.readFileSync(matchArtifactPath, "utf-8"));
  fs.writeFileSync(
    path.join(libDir, "match-verifier-abi.json"),
    JSON.stringify(matchArtifact.abi, null, 2) + "\n"
  );
  console.log("Saved SkillProofMatchVerifier ABI to lib/match-verifier-abi.json");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
