import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying ZK Verifier contracts with account:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account balance:", ethers.formatEther(balance), "C2FLR");

  // 1. Deploy Groth16Verifier (generated by snarkjs)
  const Groth16Factory = await ethers.getContractFactory("Groth16Verifier");
  const groth16Verifier = await Groth16Factory.deploy();
  await groth16Verifier.waitForDeployment();
  const groth16Address = await groth16Verifier.getAddress();
  console.log("Groth16Verifier deployed to:", groth16Address);

  // 2. Deploy SkillProofZKVerifier (wrapper)
  const ZKFactory = await ethers.getContractFactory("SkillProofZKVerifier");
  const zkVerifier = await ZKFactory.deploy(groth16Address);
  await zkVerifier.waitForDeployment();
  const zkAddress = await zkVerifier.getAddress();
  console.log("SkillProofZKVerifier deployed to:", zkAddress);

  // 3. Update deployments.json
  const libDir = path.join(__dirname, "..", "lib");
  const deploymentsPath = path.join(libDir, "deployments.json");
  const deployments = JSON.parse(fs.readFileSync(deploymentsPath, "utf-8"));

  const network = await ethers.provider.getNetwork();
  const networkName = network.chainId === 114n ? "coston2" : "localhost";

  if (!deployments[networkName]) {
    deployments[networkName] = {};
  }
  deployments[networkName].Groth16Verifier = groth16Address;
  deployments[networkName].SkillProofZKVerifier = zkAddress;
  fs.writeFileSync(deploymentsPath, JSON.stringify(deployments, null, 2) + "\n");
  console.log("Updated lib/deployments.json");

  // 4. Extract and save ABIs
  const groth16ArtifactPath = path.join(
    __dirname, "..", "artifacts", "contracts",
    "Groth16Verifier.sol", "Groth16Verifier.json"
  );
  const groth16Artifact = JSON.parse(fs.readFileSync(groth16ArtifactPath, "utf-8"));
  fs.writeFileSync(
    path.join(libDir, "zk-verifier-abi.json"),
    JSON.stringify(groth16Artifact.abi, null, 2) + "\n"
  );
  console.log("Saved Groth16Verifier ABI to lib/zk-verifier-abi.json");

  const zkArtifactPath = path.join(
    __dirname, "..", "artifacts", "contracts",
    "SkillProofZKVerifier.sol", "SkillProofZKVerifier.json"
  );
  const zkArtifact = JSON.parse(fs.readFileSync(zkArtifactPath, "utf-8"));
  fs.writeFileSync(
    path.join(libDir, "zk-wrapper-abi.json"),
    JSON.stringify(zkArtifact.abi, null, 2) + "\n"
  );
  console.log("Saved SkillProofZKVerifier ABI to lib/zk-wrapper-abi.json");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
